CREATE TABLE IF NOT EXISTS songs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    album VARCHAR(255),
    audio_url VARCHAR(2048) NOT NULL,
    artwork_url VARCHAR(2048),
    duration INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    songId INT NOT NULL,
    playedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (songId) REFERENCES songs(id) ON DELETE CASCADE
);
